'''
Input: family data (emails,names, relationship status)
Output: secret santa assignments where married couples can't have each other and you don't get the same person
you got last year

'''
import csv
import random

santaDict = {} # {gifter: giftee}
spouseDict = {} # {name : spouse}
lastyearDict = {} # {name: person they had last year}
idDict = {} # {id (int) : name (str)}

file = 'santaData.csv'

# data has fields id, name, spouse, lastyear, email
with open(file, 'r') as santaData:
    data = csv.DictReader(santaData, delimiter = ',')
    count = sum(1 for _ in data)

    santaData.seek(0)
    next(data)
       
    for row in data:
        spouseDict[row['name']] = row['spouse']
        idDict[int(row['id'])] = row['name']
        lastyearDict[ row['name'] ] = row['lastyear']

# initialize random queue
def goodlist(x):
    for i in x:
        iname = idDict[i]
        xiname = idDict[ x[i] ]
        if x[i] == i:
            return False
        elif spouseDict[iname] == xiname:
            return False
        elif lastyearDict[iname] == xiname:
            return False
    return True

randlist = list(range(0, count))
random.shuffle(randlist)

while not goodlist(randlist):
    random.shuffle(randlist)


# assign secret santas
for i in randlist:
    iname = idDict[i]
    randname = idDict[ randlist[i] ]
    santaDict[iname] = randname

print(santaDict)

# email the results
# For more info, see http://naelshiab.com/tutorial-send-email-python/
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

email = ""
password = ""
server = smtplib.SMTP('smtp.gmail.com',587)
server.starttls()
server.login(email, password)

with open(file, 'r') as santaData:
    data = csv.DictReader(santaData, delimiter = ',')
    for row in data:
        santaname = row['name']
        message = MIMEMultipart()
        message['From'] = email
        message['To'] = row['email']
        message['Subject'] = "Casias Christmas 2017"
        body = '''Hey %s,

We're having Christmas in Dunsmuir! Tamales, pajamas, gingerbread houses, and cookies galore! We will be continuing our tradition of secret stockings!  This year, you will be filling the stocking for %s!

Also plan to bring one gift to contribute to this year's White Elephant gift exchange! Can't wait to celebrate!

Love,
Chuck's Computer Elf

P.S. These Secret Santa assignments and this email were generated by Chuck's computer program, so no one will be able to tell you who you have.You will have to refer to this email. Still confused? Call someone. Cheers!
        ''' %(santaname, santaDict[santaname])
        message.attach(MIMEText(body,'plain'))
        text = message.as_string()
        server.sendmail(email, row['email'] , text)

server.quit()
