"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

def make_dict(string):
	dictionary = {}
	for letter in string:
		if letter not in dictionary:
			dictionary[letter] = 1
		else:
			dictionary[letter] += 1
	return dictionary

def findTheDifference(s,t):
	dict_s = make_dict(s)
	dict_t = make_dict(t)
	difference_dict = {}
	for letter in t:
		if letter in dict_s:
			difference_dict[letter] = dict_t[letter] - dict_s[letter]
		else:
			return letter
	for key in difference_dict:
		if difference_dict[key] > 0:
			return key

s = 'abccd'
t = 'bacdcg'

print(findTheDifference(s,t))

	
